cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('offer/', views.offer, name = 'offer'),
    path('order_created/', views.order_created, name = 'order_created'),
    path('add_item_ajax/', views.add_item_ajax, name = 'add_item_ajax'),
    path('delete_from_cart_ajax/', views.delete_from_cart_ajax, name = 'delete_from_cart_ajax'),
    path('update_cart_info_ajax/', views.update_cart_info_ajax, name = 'update_cart_info_ajax'),
    path('add_quantity_ajax/', views.add_quantity_ajax, name = 'add_quantity_ajax'),
    path('remove_quantity_ajax/', views.remove_quantity_ajax, name = 'remove_quantity_ajax'),
    path('check_in_cart_ajax/', views.check_in_cart_ajax, name = 'check_in_cart_ajax'),
    path('favorite/', views.favorite, name = 'favorite'),
    path('favorite_add_or_delete_ajax', views.favorite_add_or_delete_ajax, name = 'favorite_add_or_delete_ajax'),
    path('update_cart_total_ajax', views.update_cart_total_ajax, name = 'update_cart_total_ajax'),
    path('update_fav_total_ajax', views.update_fav_total_ajax, name = 'update_fav_total_ajax'),
]

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('contacts/', views.contacts, name = 'contacts'),
    path('delivery/', views.delivery, name = 'delivery'),
    path('payment/', views.payment, name = 'payment'),
    path('<int:cat_id>', views.category, name = 'category'),
    path('<int:cat_id>/<int:dest_id>', views.destination, name = 'destination'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('products/on_sale', views.on_sale, name = 'on_sale'),
    path('filter_products_ajax', views.filter_products_ajax, name = 'filter_products_ajax'),
    path('load_products_ajax', views.load_products_ajax, name = 'load_products_ajax'),
    path('search_form', views.search_form, name = 'search_form'),
    path('search/<search_query>', views.search, name = 'search')
]

santeh/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings # to import static in deployment
from django.conf.urls.static import static # to import static in deployment

urlpatterns = [
    path('', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

class Favorite(models.Model):
    created_at = models.DateTimeField(auto_now_add = True) 
    session_key = models.CharField(max_length = 200)
    def get_items(self):
        items = self.favoriteitem_set.all()
        return len(items)

class Favoriteitem(models.Model):
    favorite = models.ForeignKey(Favorite, on_delete = models.CASCADE, default = None,
    blank = True, null = True)
    pr_id = models.IntegerField(default = None)

class Cart(models.Model):  
    created_at = models.DateTimeField(auto_now_add = True) 
    session_key = models.CharField(max_length = 200)

    def get_total(self):
        total = 0
        for item in self.item_set.all():
            total += item.price * item.quantity
        return total
    def items_in_cart(self):
        return len(self.item_set.all())
    


class Order(models.Model):

    name = models.CharField(max_length = 200, default = '')
    phone = models.CharField(max_length = 50, default = '')
    email = models.CharField(max_length = 200, default = '')
    delivery = models.CharField(max_length = 1000, default = '')
    payment = models.CharField(max_length = 200, default = '')

    def __str__(self):
        return self.name
    
    
class Item(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE, default = None,
    blank = True, null = True)
    order = models.ForeignKey(Order, on_delete = models.DO_NOTHING, 
    default = None, blank = True, null = True)

    pr_id = models.IntegerField(default = 0)
    name = models.CharField(max_length = 200, default = '')
    price = models.IntegerField(default = 0)
    sale_price = models.IntegerField(default = 0)
    quantity = models.IntegerField(default = 1)
    imgsrc = models.ImageField(upload_to="static/images/products", default = '')

    def product_price(self):
        return self.price * self.quantity
    def product_sale_price(self):
        return self.sale_price * self.quantity
    def __str__(self):
        return self.name 

    def discount_perc(self):
            return int((self.sale_price / self.price) * 100)
    def discount_val(self):
        return int(self.price - self.sale_price) * self.quantity
    def has_sale(self):
        if self.sale_price > 0:
            return True
        else:
            return False
    

def delete_all_cart():
    carts = Cart.objects.all()
    items = Item.objects.all()
    orders = Order.objects.all()
    fav = Favorite.objects.all()
    fav_items = Favoriteitem.objects.all()
    fav.delete()
    print('fav is deleted')
    fav_items.delete()
    print('fav items are deleted')
    carts.delete()
    print("All carts are deleted")
    items.delete()
    print("All items are deleted")
    orders.delete()
    print("All orders are deleted")

cart/views.py
from django.shortcuts import render

from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from santeh.settings import * 
from products.models import * 



def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key

def get_or_create_cart(request):
    session_key = get_session_key(request)
    current_cart = Cart.objects.get_or_create(
        session_key = session_key,
    )[0],
    return current_cart[0]

def get_or_create_favorite(request):
    session_key = get_session_key(request)
    current_favorite = Favorite.objects.get_or_create(
        session_key = session_key
    )[0]
    return current_favorite


def index(request):
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)

    categories = Category.objects.all()
    return render(request, 'cart/index.html', {
        'categories': categories,
        'cart': cart,
        'fav_main': fav,
        'session_key': session_key,
    })

def offer(request):
    session_key = get_session_key(request)
    cart = get_or_create_cart(request)

    categories = Category.objects.all()
    return render(request, 'cart/offer.html', {
        'categories': categories,
        'cart': cart,
    })

def order_created(request):
    session_key = get_session_key(request)

    categories = Category.objects.all()
    return render(request, 'cart/order_created.html', {
        'categories': categories,
    })


def add_item_ajax(request):
    cart = get_or_create_cart(request)
    is_new = 'yes'
    pr_id = request.GET['product_id']
    pr = Product.objects.get(
        id = pr_id,
    )
    if (Item.objects.filter(
        cart = cart,
        pr_id = pr.id,
    ).exists()):
        item = Item.objects.get(
           cart = cart,
            pr_id = pr.id, 
        )
        item.delete()
        in_cart = 'no'
        # item = Item.objects.get(
        #    cart = cart,
        #     pr_id = pr.id, 
        # )
        # item.quantity += 1
        # item.save()
    else:
        item = Item(
            cart = cart,
            pr_id = pr.id,
            name = pr.name,
            price = pr.price,
            sale_price = pr.sale_price,
            imgsrc = pr.imgsrc,
        )
        item.save()
        in_cart = 'yes'
    
    return JsonResponse({
        'is_new': is_new,
        'in_cart': in_cart,
    }, status = 200 )

def delete_from_cart_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['item_id']
    item = Item.objects.get(
        cart = cart,
        id = item_id
    )
    cart.item_set.remove(item)
    return JsonResponse({
        'deleted': 'yes'
    }, status = 200)

def update_cart_info_ajax(request):
    cart = get_or_create_cart(request)
    cart_total = cart.get_total()
    cart_quantity = cart.item_set.count()
    return JsonResponse({
        'cart_total': cart_total,
        'cart_quantity': cart_quantity,
        'deleted': 'yes'
    }, status = 200)

def remove_quantity_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['item_id']
    item = Item.objects.get(
        cart = cart,
        id = item_id,
    )
    if item.quantity == 1:
        item.delete()
        is_removed = 'yes'
        return JsonResponse({
        'is_removed': is_removed,
    }, status = 200)
    else:
        item.quantity -= 1
        item.save()
        is_removed = 'no'
        if (item.has_sale()):
            has_sale = 'yes'
            pr_price = item.product_price()
            pr_sale = item.product_sale_price()
            discount_val = item.discount_val()
            return JsonResponse({
            'has_sale': has_sale,
            'is_removed': is_removed,
            'item_price': pr_price,
            'item_sale': pr_sale,
            'item_discount_val': discount_val,
            'item_quantity': item.quantity,
        }, status = 200)
        else:
            has_sale = 'no'
            pr_price = item.product_price()
            return JsonResponse({
            'has_sale': has_sale,
            'is_removed': is_removed,
            'item_price': pr_price,
            'item_quantity': item.quantity,
        }, status = 200)

        
    

def add_quantity_ajax(request):
    print('request is here')
    cart = get_or_create_cart(request)
    try:
        request.GET['from_prpage']
        item_id = request.GET['item_id']
        item = Item.objects.get(
            cart = cart,
            pr_id = item_id,
        )
    except:
        item_id = request.GET['item_id']
        item = Item.objects.get(
        cart = cart,
        id = item_id,
        )

    
    
    
    item.quantity += 1
    item.save()

    if item.has_sale():
        has_sale = 'yes'
        pr_price = item.product_price()
        pr_sale = item.product_sale_price()
        discount_val = item.discount_val()
        return JsonResponse({
            'has_sale': has_sale,
            'item_price': pr_price,
            'item_sale': pr_sale,
            'item_discount_val': discount_val,
            'item_quantity': item.quantity,
        }, status = 200)
    else:
        has_sale = 'no'
        pr_price = item.product_price()
        return JsonResponse({
        'has_sale': has_sale,
        'item_price': pr_price,
        'item_quantity': item.quantity,
    }, status = 200)

def check_in_cart_ajax(request):
    cart = get_or_create_cart(request)
    item_id = request.GET['product_id']
    in_cart = ''
    if (Item.objects.filter(
        cart = cart,
        pr_id = item_id).exists()):
        in_cart = 'yes'
        current_item = Item.objects.get(
            cart = cart,
            pr_id = item_id
        )
        return JsonResponse({
            'in_cart': in_cart,
            'quantity': current_item.quantity,
        }, status = 200)
    else:
        in_cart = 'no'
        return JsonResponse({
            'in_cart': in_cart,
        }, status = 200)

def favorite(request):
    session_key = get_session_key(request)
    current_fav = get_or_create_favorite(request)
    fav_items = current_fav.favoriteitem_set.all()
    fav_items = fav_items.values_list('pr_id')
    fav_items = Product.objects.filter(
        id__in = fav_items
    )
    cart = get_or_create_cart(request)
    categories = Category.objects.all()
    products = Product.objects.all()
    return render(request, 'cart/favorite.html', {
        'categories': categories,
        # 'products': fav_items,
        'session_key': session_key,
        'fav_main': current_fav,
        'cart': cart,
        'fav_items': fav_items,
    })


def favorite_add_or_delete_ajax(request):
    pr_id = request.GET['product_id']
    exist = ''
    fav = get_or_create_favorite(request)
    fav_items = fav.favoriteitem_set.all()
    if (fav_items.filter(
        pr_id = pr_id,
    ).exists()):
        curr_item = fav_items.get(pr_id = pr_id)
        print(curr_item)
        curr_item = Favoriteitem.objects.get(id = curr_item.id)
        curr_item.delete()

        exist = 'deleted'
        return JsonResponse({
            'exist': exist,
        }, status = 200)
    else:
        item = Favoriteitem(
            favorite = fav,
            pr_id = pr_id
        )
        item.save()
        exist = 'added'
        return JsonResponse({
            'exist': exist,
        }, status = 200)

def update_cart_total_ajax(request):
    cart = get_or_create_cart(request)
    cart_total = cart.items_in_cart()
    return JsonResponse({
        'cart_total': cart_total,
    }, status = 200)

def update_fav_total_ajax(request):
    fav = get_or_create_favorite(request)
    fav_total = fav.get_items()
    return JsonResponse({
        'fav_total': fav_total,
    }, status = 200)

templates/cart/favorite.html
{% extends '../products/base.html' %}

{% block content %}

{% include './blocks/space20.html' %}

<div class="nice__title2__left">
    Избранные товары
</div>


<div class="favorite__main__block">



{% comment %} {% for item in fav_items.all  %}

{{ item.pr_id }}

{% endfor %}
{{ fav_items }} {% endcomment %}

{% include './blocks/space20.html' %}

<div class="products__list__wrapper
favorite_items">

    {% for product in fav_items  %}
        {% include '../products/blocks/product_single.html' %}
    {% endfor %}

</div>


{% include './blocks/space20.html' %}




{% include './blocks/space20.html' %}

<div class="continue__shopping">
    <a id="continue__shopping"
    href="{% url 'products:index' %}">
        Продолжить покупки
    </a>
</div>

</div>

<div class="favorite__empty__block">

{% include './blocks/favorite_empty.html' %}

</div>


<script>
    checkFavoriteEmpty()
    function checkFavoriteEmpty() {
        var item = $(".favorite_items").children().length

        if (item ==  0) {
            $(".favorite__empty__block").addClass("show")
            $(".favorite__main__block").addClass("hide")
        }
    }
</script>



{% endblock content %}

templates/cart/index.html
{% extends '../products/base.html' %}

{% block content %}

<div class="cart__main__title">

    {% include './blocks/space20.html' %}
    <div class="nice__title2__left">
        Корзина 
    </div>
</div>


{% include './blocks/space20.html' %}

<div class="cart__main">

<div class="cart__container">
    <div class="cart__container__products">

        {% for item in cart.item_set.all  %}
            {% include './blocks/checkout_item.html' %}
        {% endfor %}
        
    </div>


    <div class="cart__container__checkout">
        <div class="cart__container__checkout__content">
        <a class="cart__checkout__button"
        href="{% url 'cart:offer' %}">
                <span>
                Перейти к оформлению
                </span>
        </a>
        <span id="checkout_sub_text">
            Доступные способы доставки и методы оплаты можно выбрать при оформлении заказа
        </span>
        <div class="your__cart__block">
            <span class="your__cart__block__title">
                Ваша Корзина
            </span>
            <span class="your__cart__block__value">
                Общее кол-во: {{ cart.item_set.count }}
            </span>
        </div>
        <div class="your__cart__block">
            <span class="your__cart__block__title2">
                Товары (2)
            </span>
            <span class="your__cart__block__value2">
                {{ cart.get_total }} &#8381;
            </span>
        </div>
        <div class="your__cart__block">
            <span class="your__cart__block__title2">
                Скидка
            </span>
            <span class="your__cart__block__value3">
                - 3600 &#8381;
            </span>
        </div>
        <div class="your__cart__block">
            <span class="your__cart__block__title3">
                Общая стоимость
            </span>
            <span class="your__cart__block__value4">
                {{ cart.get_total }} &#8381;
            </span>
        </div>
    
        
        
        </div>
        
    </div>

</div>

</div>

{% include './blocks/empty_cart.html' %}

<script>
    checkEmpty()
    $(".main__site__wrapper__main").addClass("bg1")
    
    $(".item_btn_deletefromcart").click(function() {
        console.log('clicked to delete')
        var item_id = $(this).attr("value")
        $.ajax({
            url: "{% url 'cart:delete_from_cart_ajax' %}",
            data: {
                'item_id': item_id
            },
            success: function(data) {
                console.log(data)
                var current_item = $(".cart__container__products__item#" +
                item_id)
                console.log(current_item)
                $(current_item).remove()
                updateCartInfo()
                checkEmpty()
                updateCartTotal()
            }
        });
    });

    function updateCartInfo() {
        $.ajax({
            url: "{% url 'cart:update_cart_info_ajax' %}",
            data: {

            },
            success: function(data) {
                console.log(data)
                cart_total = data['cart_total']
                cart_quantity = data['cart_quantity']
                $(".your__cart__block__value").html(cart_quantity)
                $(".your__cart__block__value4").html(cart_total)
                $(".your__cart__block__value2").html(cart_total)
            }
        })
    }

    function checkEmpty() {
        var pr_cont = $(".cart__container__products")
        var cont_length = pr_cont.children().length
        if (cont_length == 0) {
            console.log('container is null')
            $(".cart__main").addClass("hide")
            $(".empty__cart__container").addClass("show")
        }
    }

    $(".cart__removequ").click(function() {
        var item_id = $(this).attr("value")
        //console.log(item_id)
        $.ajax({
            url: "{% url 'cart:remove_quantity_ajax' %}",
            data: {
                'item_id': item_id,
            },
            success: function(data) {
                var is_removed = data['is_removed']
                if (is_removed == 'yes') {
                  var current_item = $(".cart__container__products__item#" +
                  item_id)
                  console.log(current_item)
                  $(current_item).remove()  
                  updateCartTotal()
                }
                else {
                   var item_quantity = data['item_quantity']
                   $(".cart__container__products__item__count__main__value#itemqu"+item_id).html(item_quantity)
                    var has_sale = data['has_sale']
                    if (has_sale == 'yes') {
                        var item_price = data['item_price']
                        console.log(item_price)
                        var item_sale = data['item_sale']
                        var item_discount_val = data['item_discount_val']
                        $(".cart__container__products__item__price__sale#saleval"+item_id).html(item_sale)
                        $(".cart__price__reg1#reg1price"+item_id).html(item_price)
                        $(".discount__valueset#discval"+item_id).html(item_discount_val)
                    } else {
                        var item_price = data['item_price']
                        $(".cart__container__products__item__price__sale#regval2"+item_id).html(item_price)
                    }
                }
                checkEmpty()
                updateCartInfo()
            }
        })
    })
    $(".item__addqu").click(function() {
        var item_id = $(this).attr("value")
        $.ajax({
            url: "{% url 'cart:add_quantity_ajax' %}",
            data: {
                'item_id': item_id,
            },
            success: function(data) {
                var has_sale = data['has_sale']
                var item_quantity = data['item_quantity']
                $(".cart__container__products__item__count__main__value#itemqu"+item_id).html(item_quantity)
                if (has_sale == 'yes') {
                    var item_price = data['item_price']
                    var item_sale = data['item_sale']
                    var item_discount_val = data['item_discount_val']
                    $(".cart__container__products__item__price__sale#saleval"+item_id).html(item_sale)
                    $(".cart__price__reg1#reg1price"+item_id).html(item_price)
                    $(".discount__valueset#discval"+item_id).html(item_discount_val)
                } else {
                    var item_price = data['item_price']
                    $(".cart__container__products__item__price__sale#regval2"+item_id).html(item_price)
                }
                updateCartInfo()
            },
            
        });
    })
</script>


{% endblock content %}

templates/cart/offer.html
{% extends '../products/base.html' %}
{% load products_extras %}
{% load static %}

{% block content %}

<div class="cart__main__title">

    {% include './blocks/space20.html' %}
    <div class="nice__title2__left">
        Оформление заказа
    </div>

</div>

<div class="offer__page__container">
    <div class="offer__page__block1">
        <div class="offer__page__block1__sub">
            <div class="offer__page__block1__sub__title">
                <span>
                    Контактные данные
                </span>
            </div>
            <div class="offer__page__block1__sub__content">

                <div class="offer__page__block1__sub__content__form">
                
                <input type="text"
                placeholder="Имя и Фамилия"
                autocomplete="off"
                class="cart__input">
                <input type="text"
                placeholder="Телефон"
                autocomplete="off"
                class="cart__input">
                <input type="text"
                placeholder="Почта"
                autocomplete="off"
                class="cart__input">
                </div>

            </div>


            <div class="offer__page__block1__sub__title">
                <span>
                    Способ доставки
                </span>
            </div>

            <div class="delivery__block__main">
                <div class="delivery__block__main__card
                delivery__method"
                data-toogle="#cart_input_cura">
                    <span>
                        Курьером по Крыму
                    </span>
                </div>
                <div class="delivery__block__main__card
                delivery__method"
                data-toogle="#cart_input_own">
                    <span>
                        Самовывоз - бесплатно
                    </span>
                </div>
            </div>


            <div class="delivery__subinfo__container">

            <input type="text"
                placeholder="Адрес доставки (городо, улица, дом, квартира)"
                autocomplete="off"
                class="cart__input"
                id="cart_input_cura">
            <span
            id="cart_input_own">
                Адрес самовывоза: г. Симферополь, переулок Заводской, дом 33
            </span>
            </div>


            <div class="offer__page__block1__sub__title">
                <span>
                    Способ оплаты
                </span>
            </div>

            <div class="delivery__block__main">
                <div class="delivery__block__main__card
                payment__method">
                    <span>
                        Наличными при получении
                    </span>
                </div>
                <div class="delivery__block__main__card
                payment__method">
                    <span>
                        Безналичный расчет
                    </span>
                </div>
            </div>


        </div>
    </div>
    <div class="offer__page__block2">
        <div class="offer__page__block2__content">
            <div class="offer__page__block2__content__item">
                <div class="offer__page__block2__content__item__first">
                    <span class="your__cart__block__title">
                        Ваш заказ
                    </span>
                </div>
                <div class="offer__page__block2__content__item__second">
                    <a class="offer__cart__back"
                    href="{% url 'cart:index' %}">
                        Редактировать
                    </a>
                </div>
            </div>

            {% for item in cart.item_set.all  %}

            {% modify_imgsrc item.imgsrc as imgsrc %}

            <div class="offer__page__block2__content__item">

                <div class="offer__page__block2__content__item__first">
                
                    <div class="offer__page__block2__content__item__prinfo">
                        <img src="{% static 'images/products'%}{{imgsrc}}" alt="">
                        <div class="offer__page__block2__content__item__prinfo__second">
                            <a class="offer__page__block2__content__item__prinfo__second__name"
                            href="{% url 'products:product' item.pr_id %}">
                                {{ item.name }}
                            </a>
                            <span class="offer__page__block2__content__item__prinfo__second__name">
                                {{ item.quantity }} шт.
                            </span>
                        </div>
                    </div>
                </div>
                <div class="offer__page__block2__content__item__second">
                    <span>
                        {{ item.price }}
                    </span>
                </div>

            </div>

            {% endfor %}

        <div class="offer__page__block2__content__item">
            <div class="offer__page__block2__content__item__first">
                <span class="your__cart__block__title2">
                    Баллов за покупку
                </span>
            </div>
            <div class="offer__page__block2__content__item__second">
                <span class="your__cart__block__value3">
                    +581
                </span>
            </div>
        </div>
        <div class="offer__page__block2__content__item">
            <div class="offer__page__block2__content__item__first">
                <span class="your__cart__block__title3">
                    Итого
                </span>
            </div>
            <div class="offer__page__block2__content__item__second">
                <span class="your__cart__block__value4">
                    {{ cart.get_total }} Р
                </span>
            </div>
        </div>

        <div class="">
            <a class="cart__checkout__button">
                <span>
                    Разместить заказ
                </span>
            </a>
        </div>


        </div>
    </div>
</div>


<script>
    $(".main__site__wrapper__main").addClass("bg1")

    $('.delivery__method').click(function() {
        setDeliveryActive(this)
    })

    $(".payment__method").click(function() {
        setPaymentActive(this)
    })

    $(".cart__checkout__button").click(function() {
        window.location = "{% url 'cart:order_created' %}"
    })

</script>

{% endblock content %}

templates/cart/order_created.html
{% extends '../products/base.html' %}

{% block content %}
    <div class="order__created__container">
        <i class="gg-check created__check">
        </i>
        <div class="order__created__container__title">
            Ваш заказ размещен!
        </div>
        <div class="order__created__container__subtitle">
            В ближайшее время с вами свяжется менеджер.
        </div>
        <div class="order__created__container__link">
            <a href="{% url 'products:index' %}">
                <span class="order__created__container__button">
                    Продолжить покупки
                </span>
            </a>
            <a href="#">
                <span class="order__created__container__button">
                    Личный кабинет
                </span>
            </a>
        </div>
    </div>
{% endblock content %}