cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('offer/', views.offer, name = 'offer'),
    path('order_created/', views.order_created, name = 'order_created'),
    path('add_item_ajax/', views.add_item_ajax, name = 'add_item_ajax'),
    path('delete_from_cart_ajax/', views.delete_from_cart_ajax, name = 'delete_from_cart_ajax'),
    path('update_cart_info_ajax/', views.update_cart_info_ajax, name = 'update_cart_info_ajax'),
    path('add_quantity_ajax/', views.add_quantity_ajax, name = 'add_quantity_ajax'),
    path('remove_quantity_ajax/', views.remove_quantity_ajax, name = 'remove_quantity_ajax'),
    path('check_in_cart_ajax/', views.check_in_cart_ajax, name = 'check_in_cart_ajax'),
    path('favorite/', views.favorite, name = 'favorite'),
    path('favorite_add_or_delete_ajax', views.favorite_add_or_delete_ajax, name = 'favorite_add_or_delete_ajax'),
    path('update_cart_total_ajax', views.update_cart_total_ajax, name = 'update_cart_total_ajax'),
    path('update_fav_total_ajax', views.update_fav_total_ajax, name = 'update_fav_total_ajax'),
]

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('contacts/', views.contacts, name = 'contacts'),
    path('delivery/', views.delivery, name = 'delivery'),
    path('payment/', views.payment, name = 'payment'),
    path('<int:cat_id>', views.category, name = 'category'),
    path('<int:cat_id>/<int:dest_id>', views.destination, name = 'destination'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('products/on_sale', views.on_sale, name = 'on_sale'),
    path('filter_products_ajax', views.filter_products_ajax, name = 'filter_products_ajax'),
    path('load_products_ajax', views.load_products_ajax, name = 'load_products_ajax'),
    path('search_form', views.search_form, name = 'search_form'),
    path('search/<search_query>', views.search, name = 'search')
]

santeh/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings # to import static in deployment
from django.conf.urls.static import static # to import static in deployment

urlpatterns = [
    path('', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    slug = models.CharField(default = '', max_length = 300)
    name = models.CharField(default = '', max_length = 300)
    imgsrc = models.ImageField(upload_to="static/images/products", default = None, blank = True )

    def __str__(self):
        return self.slug + self.name
        
class Destination(models.Model):
    name = models.CharField(default = '', max_length = 300)
    category = models.ForeignKey(Category,
    on_delete=models.CASCADE)
    def __str__(self):
        return self.name

        
class Product(models.Model):
    # attributes = models.ManyToManyField(Attributeitem)
    # attributes = models.ManyToManyField(Attribute)
    category = models.ForeignKey(Category,
    on_delete=models.CASCADE, default = None,)
    destination = models.ManyToManyField(Destination)
    
    name = models.CharField(default = '', max_length = 300)
    price = models.IntegerField(default = 0)
    sale_price = models.IntegerField(default = 0)
    description = models.CharField(default = '', max_length = 2000)
    # imgsrc = models.ImageField(upload_to='static/images', blank = True, null = True)
    imgsrc = models.ImageField(upload_to="static/images/products", default = None, blank = True, null = True)
    def __str__(self):
        return self.category.slug + self.name 
    def discount_perc(self):
        return int((self.sale_price / self.price) * 100)
    def discount_val(self):
        return int(self.price - self.sale_price)
    def has_sale(self):
        if self.sale_price > 0:
            return True
        else:
            return False


class Attribute(models.Model):
    name = models.CharField(default = '', max_length = 300) 
    category = models.ForeignKey(Category,
    on_delete=models.CASCADE, default = None,)
    # product = models.ForeignKey(Product,
    #     on_delete=models.CASCADE, default = None,
    # )
    product = models.ManyToManyField(Product)
    def __str__(self):
        return self.name 

class Attributeitem(models.Model):
    name = models.CharField(default = '', max_length = 300)
    attr = models.ForeignKey(
        Attribute, on_delete=models.CASCADE,
    )
    product = models.ManyToManyField(Product)
    def __str__(self):
        return self.name 
    
def deleteall():
    pr = Product.objects.all()
    dest = Destination.objects.all()
    ct = Category.objects.all()
    atr = Attribute.objects.all()

    atr.delete()
    attritem = Attributeitem.objects.all()
    attritem.delete()

    ct.delete()
    dest.delete()
    pr.delete()

    print('all is deleted')

products/views.py
from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from santeh.settings import * 
from cart.models import * 
import json
from django.template.loader import render_to_string



# Create your views here.

def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key

def get_or_create_cart(request):
    session_key = get_session_key(request)
    current_cart = Cart.objects.get_or_create(
        session_key = session_key,
    )[0],
    return current_cart[0]

def get_or_create_favorite(request):
    session_key = get_session_key(request)
    current_favorite = Favorite.objects.get_or_create(
        session_key = session_key
    )[0]
    return current_favorite

def get_not_active_filters():
    return ['Артикул производителя:', 
            'Комплектация:']

def index(request):
    fav = get_or_create_favorite(request)
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    categories = Category.objects.all()
    # destinations = Destination.objects.all()
    products = Product.objects.all()
    stock_products = products.filter(
        sale_price__gte = 1
    )
    stock_products = stock_products[:30]
    products = products[:50]

    template = 'products/index.html'
    page_template='products/blocks/products_list.html'

    products_smesiteli = Category.objects.filter(
        name = 'Смесители'
    )[0].product_set.all()[:10]
    products_dush = Category.objects.filter(
        name = 'Душевая программа'
    )[0].product_set.all()[:10]
    products_keramika = Category.objects.filter(
        name = 'Керамика'
    )[0].product_set.all()[:10]

    context = {
        'fav_main': fav,
        'categories': categories,
        'products': products,
        'stock_products': stock_products,
        'session_key': session_key,
        'cart': cart,
        'products_smesiteli': products_smesiteli,
        'products_dush': products_dush,
        'products_keramika': products_keramika,
    }
    if request.is_ajax():
        template = page_template
    return render(request, template, context)

def product(request, product_id):
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    current_product = Product.objects.get(id = product_id)
    categories = Category.objects.all()
    return render(request, 'products/product.html', {
        'product': current_product,
        'fav_main': fav,
        'cart': cart,
        'session_key': session_key,
        'categories': categories,
    })



def destination(request, cat_id, dest_id):
    session_key = get_session_key(request)
    current_cat = Category.objects.get(
        id = cat_id,
    )
    current_dest = Destination.objects.get(
        category = current_cat,
        id = dest_id,
    )
    products = current_dest.product_set.all()
    return render(request, 'products/dest.html', {
        'current_cat': current_cat,
        # 'current_dest': current_dest,
        'products': products,
    })

def on_sale(request):
    categories = Category.objects.all()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    products = Product.objects.filter(
        sale_price__gte = 1
    )
    context = {
        'fav_main': fav,
        'cart': cart,
        'categories': categories,
        'session_key': session_key,
        'products': products,
    }
    template = 'products/on_sale.html'
    page_template='products/blocks/products_list.html'
    if request.is_ajax():
        template = page_template
    return render(request, template, context )

def category(request, cat_id):
    print('start category view')
    not_active_filters = get_not_active_filters()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    print('cart, session_key, fav got')
    categories = Category.objects.all()
    
    current_cat = Category.objects.get(
        id = cat_id,
    )
    print('current category got')
    
    products = current_cat.product_set.all()
    # products = products[:100]
    print('products length is:', len(products))
    print('products got')

    template='products/category.html'
    page_template='products/blocks/products_list.html'

    context = {
        'page_template': page_template,
        'current_cat': current_cat,
        # 'current_dest': current_dest,
        'products': products,
        'fav_main': fav,
        'cart': cart,
        'session_key': session_key,
        'current_cat': current_cat,
        'not_active_filters': not_active_filters,
        'categories': categories,
        # 'active_filter_items': active_filter_items,
    }
    if request.is_ajax():
        print('that was an ajax request')
        template = page_template

    try:
        filters = request.GET['filters']
        print('filters is', filters)
        active_filter_items = []
        if filters:
            if len(filters) > 0:
                filters = filters.split('_')   
                # attr_list = []
                # attr_items_list = []
                # active_filter_items = []
                for f_item in filters:
                    f_item = f_item.split('-')
                    attr_id = f_item[0]
                    f_item.pop(0)
                    products = products.filter(
                        attributeitem__id__in = f_item
                    )
            context['products'] = products
            return render(request, template,
    context)
            # return JsonResponse({
            #     'result': True,
            #     'products': render_to_string(
            #         request = request,
            #         template_name = template,
            #         context = context
            #     )
            # })
    except:
        pass

    print('current template is: ', template)
    return render(request, template,
    context)

def filter_products_ajax(request):
    not_active_filters = get_not_active_filters()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    
    cat_id = request.GET['current_cat']
    filters = request.GET['filters']

    current_cat = Category.objects.get(
        id = cat_id,
    )
    
    products = current_cat.product_set.all()
    # products = Product.objects.filter(
    #     category = current_cat,
    # ) 

    active_filter_items = []

    checked_filters = []

    if len(filters) > 0:
    
        filters = filters.split('_')   
        # attr_list = []
        # attr_items_list = []
        # active_filter_items = []
        for f_item in filters:
            f_item = f_item.split('-')
            attr_id = f_item[0]
            f_item.pop(0)
            products = products.filter(
                attributeitem__id__in = f_item
            )
            for i in f_item:
                checked_filters.append(i)
            
            # attr_list.append(attr_id)
        # print(attr_list)
        # print(attr_items_list)

    print(len(products))
     
    # print(active_filter_items)

    loading_filters = request.GET['loading_filters'] 
    if loading_filters == 'no':
        # products = products[:100]
        return render(request, 'products/blocks/products_list.html', {
            'products': products,
            'fav_main': fav,
            'cart': cart,
            'session_key': session_key,
            'current_cat': current_cat,
        })
    else:
        attr = ['']
        print('start getting active filters')
        # attribute_items = []
        # attributes = current_cat.attribute_set.all()
        # for a in attributes:
        #     attribute_items.append(a.attributeitem_set.all())
        # print(attribute_items)

        # more quick method, but need to fix arguments error in sqlite3.
        products_ids = list(products.values_list('id', flat = True))
        attr = list(Attributeitem.objects.filter(
            product__id__in = products_ids
        ).values_list('id', flat = True))

        # more slow method to filter products
        # for product in products:
        #     s = list(product.attributeitem_set.all().values_list('id', flat = True))
        #     attr.append(s)
        # print('reached', attr)
                        
        
        # print('attributes filters', attr)

        # products_ids = list(products.values_list('id', flat = True))
        # attr = list(Attributeitem.objects.filter(
        #     product__id__in = products_ids
        # ).values_list('id', flat = True))
        # print('attr is: ', attr)
        # attr = []
        # for product in products: 
        #     attr_items = product.attributeitem_set.all()
        #     for i in attr_items:
        #         if i.id in attr:
        #             pass
        #         else:
        #             attr.append(i.id)
        print('end getting active filters')
        # print(attr)
        return JsonResponse({
            'active_filters': attr,
            'checked_filters': checked_filters,
        }, status = 200)


def load_products_ajax(request):
    print('start category view')
    not_active_filters = get_not_active_filters()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    print('cart, session_key, fav got')
    
    # current_cat = Category.objects.get(
    #     id = cat_id,
    # )
    products = Product.objects.all()

    template = 'products/blocks/products_list.html'

    context = {
        'fav_main': fav,
        'cart': cart,
        'session_key': session_key,
        'products': products,
        'not_active_filters': not_active_filters,
    }

templates/products/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Сантехника в Крыму</title>

</head>
<body>

    {% include './includes_css.html' %}
    {% include './includes_js.html' %}

    {% block main_header %}
    <div class="main__header__block__wrapper">

    <div id="scroll_to_top"></div>

    <div class="main__header__block">
        {% include './header.html' %}
    </div>
    {% endblock main_header %}

    </div>

    <div class="main__site__wrapper__main">


        <div class="main__site__wrapper">
            {% block content %}

            {% endblock content %}
           
        </div>
         {% include './footer.html' %}

    </div>

    {% include './blocks/scroll_to_top.html' %}


    <div class="header__results">
        {% include './blocks/search_results.html' %}
    </div>

    <script>


var sticky = new Waypoint.Sticky({
    element: $('.main__header__second'), // Add in your CSS selector sticky target
    // direction: 'down right',
  })



function update_fav_total_ajax() {
    $.ajax({
        url: "{% url 'cart:update_fav_total_ajax' %}",
        data: {
            'someinfo': 'someinfo',
        },
        success: function(data) {
            var total = data['fav_total']
            $(".count__label__heart").html(total)
        },
    })
}

function updateCartTotal() {
  $.ajax({
    url: "{% url 'cart:update_cart_total_ajax' %}",
    data: {
      'someinfo': 'someinfo',
    },
    success: function(data) {
      var total = data['cart_total']
        $(".count__label").html(total)
    }
  })
}

        $("body").on( 'click', ".product__addtocart__global", function() {
            addProductToCart(this)
            // ajax ends here
        });
        
        function changeButtonCart(in_cart, item) {
            if (in_cart == 'yes') {
                console.log(item.children())
                item.html("<span class='in__cart__buttonstyle'> Удалить с корзины </span>")
            } else {
                item.html("<span class='not__incart__buttonstyle'>В корзину</span>")
            }
        }

        function addProductToCart(product_block) {
            current_item = $(product_block)
            var current_pr_id = $(product_block).attr("value")
            // ajax start here
            $.ajax({
                url: "{% url 'cart:add_item_ajax' %}",
                data: {
                    'product_id': current_pr_id,
                },
                success: function(data) {
                    var in_cart = data['in_cart']
                        changeButtonCart(in_cart, current_item)
                        updateCartTotal()
                }
            });
        }
        function addProductToCart2(product_block) {
            current_item = $(product_block)
            var current_pr_id = $(product_block).attr("value")
            // ajax start here
            $.ajax({
                url: "{% url 'cart:add_item_ajax' %}",
                data: {
                    'product_id': current_pr_id,
                },
                success: function(data) {
                    var in_cart = data['in_cart']
                    var quantity = data['quantity']
                    updateCartTotal()
                        // changeButtonCart(in_cart, current_item)
                }
            });
        }
        function favAddDelete(item, pr_id) {
            $.ajax({
                url: "{% url 'cart:favorite_add_or_delete_ajax' %}",
                data: {
                    'product_id': pr_id,
                },
                success: function(data) {
                    console.log(data)
                    var exist = data['exist']
                    if (exist == 'added') {
                        $(item).addClass("red")
                        $(item).removeClass("white")
                    } else {
                        $(item).removeClass("red")
                        $(item).addClass("white")
                    }
                    update_fav_total_ajax()
                }
            })
        }

        $("body").on( 'click', ".add_delete_favorite", function() {
            var pr_id = $(this).attr("value")
            console.log('it is ok dude')
            favAddDelete(this, pr_id)
        })

        // $(".filter__content__large").selectize({

        // });

        $('body').on('click', '#scroll_top_link', function() {
            $([document.documentElement, document.body]).animate({
        scrollTop: $("#scroll_to_top").offset().top
    }, 1200);
        })


    $(document).mouseup(function(e) {
    var container = $(".header__results");

    // if the target of the click isn't the container nor a descendant of the container
    if (!container.is(e.target) && container.has(e.target).length === 0) 
    {
        closeSearchResults()

    }
});

    $('.input_search').on('click', function() {
        if ($('.search__result__item').length > 0) {
            showSearchResults()
        }  
    })
    $("input[name=search_input]").on( 'keyup', function() {
        var s_query = $(this).val()
        $('.input_search').attr("value", s_query) 
        console.log('handled updated')
        console.log(s_query)
        $.ajax({
            url: "{% url 'products:search_form' %}",
            data: {
                's_query': s_query,
            }, success(data) {
                showSearchResults()
                var d = data
                $(".header__results").html('')
                $(".header__results").html(d)
            }   
        })
    })

    $("body").on('click', ".search__results__button__link", function() {
        var s_query = $('.input_search').val()
        var v = '/' + s_query
        window.location = "{% url 'products:search' search_query=123 %}".replace('/123', v)
    })

    $(".header__second__search__form").on("submit", function(e) {
        e.preventDefault();
        var s_query = $('.input_search').val()
        var v = '/' + s_query
        window.location = "{% url 'products:search' search_query=123 %}".replace('/123', v)
    })


    function showSearchResults() {
        $(".header__results").addClass("show")
    }
    function closeSearchResults() {
        $(".header__results").removeClass("show")
    }


    </script>

</body>
</html>

templates/products/category.html
{% extends './base.html' %}

{% block content %}




<div class="nice__title__center">
    {{ current_cat.name }}
</div>



{% include './blocks/space20.html' %}

<div class="category__main__content">

{% include './blocks/category_container.html' %}

</div>

<script>
    // loadProducts()

    function loadProducts() {
        // console.log('start function')
        $.ajax({
            url: "{% url 'products:load_products_ajax' %}", 
            data: {

            },
            success: function() {
                $(".products__list__wrapper").html(data)
            }
        })
    }

    //filterProducts()

    function filterProducts() {
        var filters_all = collectFilters()
        // console.log(filters_all)

        const csrftoken = Cookies.get('csrftoken');
        // console.log(csrftoken)
        // console.log("{{current_cat.id}}")
        $.ajax({
            // type: 'POST',
            // headers: {
            //     "X-CSRFToken": csrftoken,
            // },
            url: "{% url 'products:category' current_cat.id %}?" + 
            "filters=" + filters_all,
            data: {
                'current_cat': "{{ current_cat.id }}", 
                'loading_filters': 'no',
            },
            success: function(data) {
                // console.log(data['products'])
                $(".products__list__wrapper").html(data) 
                var path = "{{ current_cat.id }}" + "?filters=" + 
                filters_all
                window.history.pushState({}, null, path),
                // $(".category__main__content").html(data)
                $(".endless_more").html("Показать еще")
            } 
        })
    }

    function collectFilters() {
        // get all filter items on the page
        items = $(".filter__item")
        // console.log(items)

        var filter_items  = []
        for (k = 0; k < items.length; k++) {
            
            var curr_item = $(items[k])

            content_items = $(curr_item).children('.filter__content').children('.filter__content__item')
            var allcontents = []
            for (i = 0; i < content_items.length; i++) {
                if ($(content_items[i]).hasClass("active")) {

                    cont_val = $(content_items[i]).attr("value")
                    allcontents = allcontents.concat(cont_val)
                }
            }
            var attr_id = $(curr_item).attr("value")
            if (allcontents.length > 0) {
                var contents_str = attr_id + '-' + allcontents.join('-')
                // console.log(contents_str)
                filter_items = filter_items.concat(contents_str)
            }

        }
        // console.log(filter_items)

        filters_all = filter_items.join('_')
        return filters_all
    }

    function getFilters(filters_all) {
        // console.log(filters_all)
        const csrftoken = Cookies.get('csrftoken');
        $.ajax({
            // type: 'GET',
            // headers: {
            //     "X-CSRFToken": csrftoken,
            // },
            url: "{% url 'products:filter_products_ajax' %}?" + 
            "filters=" + filters_all,
            data: {
                'current_cat': "{{ current_cat.id }}", 
                'loading_filters': 'yes',
            },
            success: function(data) {
                var active_filters = data['active_filters']
                var checked_filters = data['checked_filters']
                filterFilters(active_filters, checked_filters)
                setCheckedFiltersWidget()
            } 
        })
    }

    function filterFilters(active_filters, checked_filters) {
        if (active_filters.length > 0) {
            console.log(checked_filters)
            var filters = $(".filter__content__item")
            for(i = 0; i < filters.length; i++) {
                var current_filter = $(filters[i])
                var current_filter_value = $(filters[i]).attr("value")
                var contains = active_filters.includes(parseInt(current_filter_value))
                var is_active = checked_filters.includes(current_filter_value)

                if (contains == false) {
                    $(current_filter).addClass("deactive_filter")
                } else {
                    $(current_filter).removeClass("deactive_filter")
                }
                if (is_active) {
                    $(current_filter).addClass("active")
                }
            }
        } else {
            $(".filter__content__item").removeClass("deactive_filter")
        }

        // sort active and deactive filters, so deactive will be on bottom
        var all_f_contents = $(".filter__content")
        for (i = 0; i < all_f_contents.length; i++) {
            var checked_items = []
            var active_items = []
            var deactive_items = []
            var current_content = $(all_f_contents[i])
            var current_content_children = $(all_f_contents[i]).children()
            for(j=0; j < current_content_children.length; j++) {
                current_item = $(current_content_children[j])
                if ($(current_item).hasClass("active")) {
                    checked_items = checked_items.concat($(current_item))
                } else if ($(current_item).hasClass("deactive_filter")) {
                    deactive_items = deactive_items.concat($(current_item))
                } else {
                    active_items = active_items.concat($(current_item))
                }
            }
            var all_filters = []
            all_filters = all_filters.concat(checked_items, active_items, deactive_items)
            // console.log(all_filters)
            $(current_content).html(all_filters)
        }
    }


    function setCheckedFiltersWidget() {
        checked_filters = getCheckedFilters()
        // console.log('checked filters are', checked_filters)
        if (checked_filters.length > 0) {
            $(".active_filters_list").html('')
            for (i = 0; i < checked_filters.length; i++) {
                var name = $(checked_filters[i]).children('div > span').text()
                var id = $(checked_filters[i]).attr("value")
                // console.log('name is ', name)
                $(".active_filters_list").append(
                "<div class='active_filter_item'><span class='active_filter_item_link' value='${id}'>${name}<i class='fa fa-close'></i></span></div>".replace('${id}', id).replace('${name}', name)
                )
            }
        } else {
            $(".active_filters_list").html('')
        }
    }

    function getCheckedFilters() {
        filter_items = $(".filter__content__item.active")
        return filter_items
    }

    $('body').on('click', '.active_filter_item_link', function() {
        filter_value = $(this).attr("value")
        current_item = $(".filter__content__item#filter-item-" + filter_value)
        $(current_item).removeClass("active")
        filterProducts()
        var filters_all = collectFilters()
        getFilters(filters_all) 
    })

    
</script>


{% endblock content %}

templates/products/footer.html
<div class="footer__wrapper">
    <div class="footer__container">
        <div class="footer__block">
            <div class="footer__block__title">
                Меню
            </div>
            <div class="footer__block__item">
                <a class="footer__block__item__link" 
                href="{% url 'products:index' %}">
                    Главная
                </a>
            </div>
            <div class="footer__block__item">
                <a class="footer__block__item__link"
                href="{% url 'products:index' %}#categories_anchor">
                    Каталог
                </a>
            </div>
            <div class="footer__block__item">
                <a class="footer__block__item__link"
                href="{% url 'products:contacts' %}">
                    Контакты
                </a>
            </div>
            <div class="footer__block__item">
                <a class="footer__block__item__link"
                href="{% url 'products:delivery' %}">
                    Доставка
                </a>
            </div>
            <div class="footer__block__item">
                <a class="footer__block__item__link"
                href="{% url 'products:payment' %}">
                    Оплата
                </a>
            </div>
        </div>
        <div class="footer__block">
            <div class="footer__block__title">
                Контакты
            </div>
            <div class="footer__block__item">
                г. Симферополь, ул. Генерала Васильева 32Г
            </div>
            <div class="footer__block__item">
                <a class="footer__block__item__tel"
                href="tel:+79782215509">
                    +7(978) 221-55-09
                </a>
            </div>
            <div class="footer__block__item">
                Пн-пт 9:00-18:00, Сб-Вс 10:00-17:00
            </div>
        </div>
    </div>
</div>

templates/products/on_sale.html
{% extends './base.html' %}

{% block content %}

    {% if products.count > 0 %}

    <div>
    
    <div class="products__list__wrapper">

        {% include './blocks/products_list.html' %} 
 
    </div> 

    </div>
        {% else %}
        {% include './blocks/space20.html' %}
{% include './blocks/space20.html' %}
<div class="favorite__empty"
id="favorite_empty_block">
    {% include './blocks/space20.html' %}
    {% include './blocks/space20.html' %}
    <span>
        На данный момент товаров по скидке нет
    </span>
    <p></p>

    {% include './blocks/space20.html' %}
    {% include './blocks/space20.html' %}
    <div class="continue__shopping">
        <a id="continue__shopping"
        href="{% url 'products:index' %}">
            Продолжить покупки
        </a>
    </div>
    {% include './blocks/space20.html' %}
    {% include './blocks/space20.html' %}
    {% include './blocks/space20.html' %}
</div>
    {% endif %}

{% endblock content %}