cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('offer/', views.offer, name = 'offer'),
    path('order_created/', views.order_created, name = 'order_created'),
    path('add_item_ajax/', views.add_item_ajax, name = 'add_item_ajax'),
    path('delete_from_cart_ajax/', views.delete_from_cart_ajax, name = 'delete_from_cart_ajax'),
    path('update_cart_info_ajax/', views.update_cart_info_ajax, name = 'update_cart_info_ajax'),
    path('add_quantity_ajax/', views.add_quantity_ajax, name = 'add_quantity_ajax'),
    path('remove_quantity_ajax/', views.remove_quantity_ajax, name = 'remove_quantity_ajax'),
    path('check_in_cart_ajax/', views.check_in_cart_ajax, name = 'check_in_cart_ajax'),
    path('favorite/', views.favorite, name = 'favorite'),
    path('favorite_add_or_delete_ajax', views.favorite_add_or_delete_ajax, name = 'favorite_add_or_delete_ajax'),
    path('update_cart_total_ajax', views.update_cart_total_ajax, name = 'update_cart_total_ajax'),
    path('update_fav_total_ajax', views.update_fav_total_ajax, name = 'update_fav_total_ajax'),
]

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('contacts/', views.contacts, name = 'contacts'),
    path('delivery/', views.delivery, name = 'delivery'),
    path('payment/', views.payment, name = 'payment'),
    path('<int:cat_id>', views.category, name = 'category'),
    path('<int:cat_id>/<int:dest_id>', views.destination, name = 'destination'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('products/on_sale', views.on_sale, name = 'on_sale'),
    path('filter_products_ajax', views.filter_products_ajax, name = 'filter_products_ajax'),
    path('load_products_ajax', views.load_products_ajax, name = 'load_products_ajax'),
    path('search_form', views.search_form, name = 'search_form'),
    path('search/<search_query>', views.search, name = 'search')
]

santeh/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings # to import static in deployment
from django.conf.urls.static import static # to import static in deployment

urlpatterns = [
    path('', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    slug = models.CharField(default = '', max_length = 300)
    name = models.CharField(default = '', max_length = 300)
    imgsrc = models.ImageField(upload_to="static/images/products", default = None, blank = True )

    def __str__(self):
        return self.slug + self.name
        
class Destination(models.Model):
    name = models.CharField(default = '', max_length = 300)
    category = models.ForeignKey(Category,
    on_delete=models.CASCADE)
    def __str__(self):
        return self.name

        
class Product(models.Model):
    # attributes = models.ManyToManyField(Attributeitem)
    # attributes = models.ManyToManyField(Attribute)
    category = models.ForeignKey(Category,
    on_delete=models.CASCADE, default = None,)
    destination = models.ManyToManyField(Destination)
    
    name = models.CharField(default = '', max_length = 300)
    price = models.IntegerField(default = 0)
    sale_price = models.IntegerField(default = 0)
    description = models.CharField(default = '', max_length = 2000)
    # imgsrc = models.ImageField(upload_to='static/images', blank = True, null = True)
    imgsrc = models.ImageField(upload_to="static/images/products", default = None, blank = True, null = True)
    def __str__(self):
        return self.category.slug + self.name 
    def discount_perc(self):
        return int((self.sale_price / self.price) * 100)
    def discount_val(self):
        return int(self.price - self.sale_price)
    def has_sale(self):
        if self.sale_price > 0:
            return True
        else:
            return False


class Attribute(models.Model):
    name = models.CharField(default = '', max_length = 300) 
    category = models.ForeignKey(Category,
    on_delete=models.CASCADE, default = None,)
    # product = models.ForeignKey(Product,
    #     on_delete=models.CASCADE, default = None,
    # )
    product = models.ManyToManyField(Product)
    def __str__(self):
        return self.name 

class Attributeitem(models.Model):
    name = models.CharField(default = '', max_length = 300)
    attr = models.ForeignKey(
        Attribute, on_delete=models.CASCADE,
    )
    product = models.ManyToManyField(Product)
    def __str__(self):
        return self.name 
    
def deleteall():
    pr = Product.objects.all()
    dest = Destination.objects.all()
    ct = Category.objects.all()
    atr = Attribute.objects.all()

    atr.delete()
    attritem = Attributeitem.objects.all()
    attritem.delete()

    ct.delete()
    dest.delete()
    pr.delete()

    print('all is deleted')

products/views.py
from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from santeh.settings import * 
from cart.models import * 
import json
from django.template.loader import render_to_string



# Create your views here.

def get_session_key(request):
    if not request.session.session_key:
        request.session.create()
    return request.session.session_key

def get_or_create_cart(request):
    session_key = get_session_key(request)
    current_cart = Cart.objects.get_or_create(
        session_key = session_key,
    )[0],
    return current_cart[0]

def get_or_create_favorite(request):
    session_key = get_session_key(request)
    current_favorite = Favorite.objects.get_or_create(
        session_key = session_key
    )[0]
    return current_favorite

def get_not_active_filters():
    return ['Артикул производителя:', 
            'Комплектация:']

def index(request):
    fav = get_or_create_favorite(request)
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    categories = Category.objects.all()
    # destinations = Destination.objects.all()
    products = Product.objects.all()
    stock_products = products.filter(
        sale_price__gte = 1
    )
    stock_products = stock_products[:30]
    products = products[:50]

    template = 'products/index.html'
    page_template='products/blocks/products_list.html'

    products_smesiteli = Category.objects.filter(
        name = 'Смесители'
    )[0].product_set.all()[:10]
    products_dush = Category.objects.filter(
        name = 'Душевая программа'
    )[0].product_set.all()[:10]
    products_keramika = Category.objects.filter(
        name = 'Керамика'
    )[0].product_set.all()[:10]

    context = {
        'fav_main': fav,
        'categories': categories,
        'products': products,
        'stock_products': stock_products,
        'session_key': session_key,
        'cart': cart,
        'products_smesiteli': products_smesiteli,
        'products_dush': products_dush,
        'products_keramika': products_keramika,
    }
    if request.is_ajax():
        template = page_template
    return render(request, template, context)

def product(request, product_id):
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    current_product = Product.objects.get(id = product_id)
    categories = Category.objects.all()
    return render(request, 'products/product.html', {
        'product': current_product,
        'fav_main': fav,
        'cart': cart,
        'session_key': session_key,
        'categories': categories,
    })



def destination(request, cat_id, dest_id):
    session_key = get_session_key(request)
    current_cat = Category.objects.get(
        id = cat_id,
    )
    current_dest = Destination.objects.get(
        category = current_cat,
        id = dest_id,
    )
    products = current_dest.product_set.all()
    return render(request, 'products/dest.html', {
        'current_cat': current_cat,
        # 'current_dest': current_dest,
        'products': products,
    })

def on_sale(request):
    categories = Category.objects.all()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    products = Product.objects.filter(
        sale_price__gte = 1
    )
    context = {
        'fav_main': fav,
        'cart': cart,
        'categories': categories,
        'session_key': session_key,
        'products': products,
    }
    template = 'products/on_sale.html'
    page_template='products/blocks/products_list.html'
    if request.is_ajax():
        template = page_template
    return render(request, template, context )

def category(request, cat_id):
    print('start category view')
    not_active_filters = get_not_active_filters()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    print('cart, session_key, fav got')
    categories = Category.objects.all()
    
    current_cat = Category.objects.get(
        id = cat_id,
    )
    print('current category got')
    
    products = current_cat.product_set.all()
    # products = products[:100]
    print('products length is:', len(products))
    print('products got')

    template='products/category.html'
    page_template='products/blocks/products_list.html'

    context = {
        'page_template': page_template,
        'current_cat': current_cat,
        # 'current_dest': current_dest,
        'products': products,
        'fav_main': fav,
        'cart': cart,
        'session_key': session_key,
        'current_cat': current_cat,
        'not_active_filters': not_active_filters,
        'categories': categories,
        # 'active_filter_items': active_filter_items,
    }
    if request.is_ajax():
        print('that was an ajax request')
        template = page_template

    try:
        filters = request.GET['filters']
        print('filters is', filters)
        active_filter_items = []
        if filters:
            if len(filters) > 0:
                filters = filters.split('_')   
                # attr_list = []
                # attr_items_list = []
                # active_filter_items = []
                for f_item in filters:
                    f_item = f_item.split('-')
                    attr_id = f_item[0]
                    f_item.pop(0)
                    products = products.filter(
                        attributeitem__id__in = f_item
                    )
            context['products'] = products
            return render(request, template,
    context)
            # return JsonResponse({
            #     'result': True,
            #     'products': render_to_string(
            #         request = request,
            #         template_name = template,
            #         context = context
            #     )
            # })
    except:
        pass

    print('current template is: ', template)
    return render(request, template,
    context)

def filter_products_ajax(request):
    not_active_filters = get_not_active_filters()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    
    cat_id = request.GET['current_cat']
    filters = request.GET['filters']

    current_cat = Category.objects.get(
        id = cat_id,
    )
    
    products = current_cat.product_set.all()
    # products = Product.objects.filter(
    #     category = current_cat,
    # ) 

    active_filter_items = []

    checked_filters = []

    if len(filters) > 0:
    
        filters = filters.split('_')   
        # attr_list = []
        # attr_items_list = []
        # active_filter_items = []
        for f_item in filters:
            f_item = f_item.split('-')
            attr_id = f_item[0]
            f_item.pop(0)
            products = products.filter(
                attributeitem__id__in = f_item
            )
            for i in f_item:
                checked_filters.append(i)
            
            # attr_list.append(attr_id)
        # print(attr_list)
        # print(attr_items_list)

    print(len(products))
     
    # print(active_filter_items)

    loading_filters = request.GET['loading_filters'] 
    if loading_filters == 'no':
        # products = products[:100]
        return render(request, 'products/blocks/products_list.html', {
            'products': products,
            'fav_main': fav,
            'cart': cart,
            'session_key': session_key,
            'current_cat': current_cat,
        })
    else:
        attr = ['']
        print('start getting active filters')
        # attribute_items = []
        # attributes = current_cat.attribute_set.all()
        # for a in attributes:
        #     attribute_items.append(a.attributeitem_set.all())
        # print(attribute_items)

        # more quick method, but need to fix arguments error in sqlite3.
        products_ids = list(products.values_list('id', flat = True))
        attr = list(Attributeitem.objects.filter(
            product__id__in = products_ids
        ).values_list('id', flat = True))

        # more slow method to filter products
        # for product in products:
        #     s = list(product.attributeitem_set.all().values_list('id', flat = True))
        #     attr.append(s)
        # print('reached', attr)
                        
        
        # print('attributes filters', attr)

        # products_ids = list(products.values_list('id', flat = True))
        # attr = list(Attributeitem.objects.filter(
        #     product__id__in = products_ids
        # ).values_list('id', flat = True))
        # print('attr is: ', attr)
        # attr = []
        # for product in products: 
        #     attr_items = product.attributeitem_set.all()
        #     for i in attr_items:
        #         if i.id in attr:
        #             pass
        #         else:
        #             attr.append(i.id)
        print('end getting active filters')
        # print(attr)
        return JsonResponse({
            'active_filters': attr,
            'checked_filters': checked_filters,
        }, status = 200)


def load_products_ajax(request):
    print('start category view')
    not_active_filters = get_not_active_filters()
    cart = get_or_create_cart(request)
    session_key = get_session_key(request)
    fav = get_or_create_favorite(request)
    print('cart, session_key, fav got')
    
    # current_cat = Category.objects.get(
    #     id = cat_id,
    # )
    products = Product.objects.all()

    template = 'products/blocks/products_list.html'

    context = {
        'fav_main': fav,
        'cart': cart,
        'session_key': session_key,
        'products': products,
        'not_active_filters': not_active_filters,
    }

templates/products/blocks/banner1.html
<div class="cost1__container">
    <div class="cost1__container__button">
        <div class="cost1__container__button__title">
            Постоянные акции и скидки!
        </div>
        <a href="{% url 'products:on_sale' %}"
        id="cost__count__link">
            Посмотреть скидки
        </a>
    </div>
</div>

templates/products/blocks/categories.html
<div id="categories_anchor"></div>
<div class="categories__main">

    <div class="cart__main__title">

        {% include './space20.html' %}
        <div class="nice__title__center">
            Категории товаров
        </div>
    </div>

    {% include './space10.html' %}

    <div class="categories__main__content">
        {% for category in categories  %}
            <a class="category__card"
            href="{% url 'products:category' category.id %}">
                <div class="category__title">
                    <span>
                        {{ category.name }}
                    </span>
                </div>
            </a>
        {% endfor %}
   

</div>

{% include './space20.html' %}
</div>

templates/products/blocks/category_container.html
<!-- {% load el_pagination_tags %} -->
<div class="category__container">

    <div class="filter__button">
        <span class="filter__button__link">
            <i class="fa fa-filter">
            </i>
            Фильтры
        </span>
    </div>
    

    {% include './space20.html' %}

    {% include './filter_block.html' %}

    <div class="category__products">  
        
        <div class="active_filters_list">
        </div>

        <div class="products__list__wrapper">

        {% include './products_list.html' %} 

        </div>
        
        </div>

    </div>

</div>

<div class="filter__wrapper__back">
</div>

<script>

    $(".filter__button__link").click(function() {
        $(".filter__wrapper").toggleClass("show")
        $(".filter__wrapper__back").toggleClass("show")
        $("body").toggleClass("hidden")
    })
    $(".filter__wrapper__back").click(function() {
        $(".filter__wrapper").toggleClass("show")
        $(".filter__wrapper__back").toggleClass("show")
        $("body").toggleClass("hidden")
    })
</script>

templates/products/blocks/filter_block.html
{% load products_extras %}


<div class="filter__wrapper">

    <div class="filter__reset__button">
        <span class="filter__reset__button__link">
            Сбросить фильтры
        </span>
    </div>
    

    {% for attr in current_cat.attribute_set.all %}

        {% if attr.name not in not_active_filters  %}

            {% if attr.attributeitem_set.all|length > 1 %}
            

        <div class="filter__item active"
        value="{{ attr.id }}">
            <div class="filter__title">
                <span>
                {{ attr }}
                </span>
                <i class="fa fa-chevron-up
                toogle_filter"></i>
            </div>
            

                {% comment %} {% if attr.attributeitem_set.all > 0 %} {% endcomment %}
                {% comment %} {% endif %} {% endcomment %}

                {% sort_attributeitems attr.attributeitem_set.all as attritems %}

                {% if attr.attributeitem_set.all|length < 15 %}

                <div class="filter__content">
                {% for attr_item in attritems  %}
                        {% include './short_filter.html' %}
                {% endfor %}
                </div>
                    {% else %}
                        {% comment %} <div class="filter__large"> {% endcomment %}
                        <div class="filter__content filter__content__large">
                            {% for attr_item in attritems %}
                            
                            <div class="filter__content__item"
                            id="filter-item-{{ attr_item.id }}"
                            value="{{ attr_item.id }}">
                                <div class="filter__content__item__checkbox">
                                    <i class="fa fa-check"></i>
                                </div>
                                <span>
                                {{ attr_item.name }}
                                </span>
                            </div>

                            {% endfor %}
                        </div>
                        {% comment %} </div> {% endcomment %}
                {% endif %}

            
        </div>

            {% endif %}

        {% endif %}

    {% endfor %}

    
</div>


<script>

    $(document).ready(function() {
        var loc = window.location.href.split("?")[1]
        if (loc) {
            filters = loc.split("=")[1]
            getFilters(filters)
        }
    })

    $(".filter__title").click(function() {
        var parent = $(this).parent()
        // console.log(parent)
        $(parent).toggleClass("active")
        $(this).children('i').toggleClass('fa-rotate-180')
    })
    $("body").on( 'click', '.filter__content__item', function() {
        console.log('clicked to filter')
        if ($(this).hasClass("deactive_filter")) {
        } else {
            $(this).toggleClass("active")
            filterProducts()
            var filters_all = collectFilters()
            getFilters(filters_all) 
        }
    })
    
    $(".filter__reset__button__link").click(function() {
        $(".filter__content__item").removeClass("active")
        filterProducts()
        var filters_all = collectFilters()
        getFilters(filters_all)
    })


</script>

templates/products/blocks/mobile__menu__container.html
<div class="mobile__menu__container__wrapper">
</div>

<div class="mobile__menu__container__close">
    <i class="fa fa-close mmc__close"></i>
</div>

<div class="mobile__menu__container">
    <a class="mmc__category mmc__main"
    href="{% url 'products:index'%}">
        <span>
            Главная
        </span>
        <i class="fa fa-chevron-right"></i>
    </a>
    <a class="mmc__category mmc__main"
    href="{% url 'products:contacts'%}">
        <span>
            Контакты
        </span>
        <i class="fa fa-chevron-right"></i>
    </a>
    <a class="mmc__category mmc__main"
    href="{% url 'products:delivery'%}">
        <span>
            Доставка
        </span>
        <i class="fa fa-chevron-right"></i>
    </a>
    <a class="mmc__category mmc__main"
    href="{% url 'products:payment'%}">
        <span>
            Оплата
        </span>
        <i class="fa fa-chevron-right"></i>
    </a>
    <div class="mmc__title">
        <span>
            Каталог товаров
        </span>
    </div>
    <div class="mmc__categories">
        {% for category in categories  %}
            <a class="mmc__category"
            href="{% url 'products:category' category.id %}">
                <span>
                    {{ category.name }}
                </span>
                <i class="fa fa-chevron-right"></i>
            </a>
        {% endfor %}
    </div>
</div>





<script>
    $("#menu__link").click(function() {
        $(".mobile__menu__container").addClass("show")
        $(".mobile__menu__container__wrapper").addClass("show")
        $(".mmc__close").addClass("show")
        $("body").addClass('hidden')
    })
    $(".mobile__menu__container__wrapper").click(function() {
        $(".mobile__menu__container").removeClass("show")
        $(".mobile__menu__container__wrapper").removeClass("show")
        $("body").removeClass('hidden')
        $(".mmc__close").removeClass("show")
    })
    $(".mmc__close").click(function() {
       $(".mobile__menu__container").removeClass("show")
        $(".mobile__menu__container__wrapper").removeClass("show")
        $("body").removeClass('hidden') 
        $(".mmc__close").removeClass("show")
    })
</script>

templates/products/blocks/popup_form.html
<div class="pform__wrap">
    <div class="pform__container">
        <div class="pform__container__title">
            бесплатный рассчет стоимости!
        </div>
        <div class="pform__container__subtitle">
            Оставьте заявку, и наш менеджер свяжется с вами.
        </div>
        
        <div class="pform__container__form">
            <input type="text"
            name="name" id="input_name"
            class="contact__input"
            placeholder="Ваше имя"
            autocomplete="off">
            <input type="text"
            name="phone" id="input_phone"
            class="contact__input"
            placeholder="Телефон*"
            autocomplete="off">
            <span class="pform__button"
            id="#pform_button">
            Отправить заявку
            </span>
        </div>
    </div>

    <div class="pform__wrap__close">
        <i class="gg-close"></i>
    </div>
</div>

<div class="pform__wrap__wrapper">

</div>

templates/products/blocks/popup_price.html
<div class="pform__wrap"
id="price_modal">
    <div class="pform__container">
        <div class="pform__container__title">
            Узнайте о снижении цены
        </div>
        <div class="pform__container__subtitle">
            Оставьте почту и мы напишем, когда цена товара снизится.
        </div>
        
        <div class="pform__container__form">
            <input type="text"
            name="email" id="email_input"
            class="contact__input"
            placeholder="Ваша почта"
            autocomplete="off">
            <span class="pform__button"
            id="#pform_button">
            Отправить
            </span>
        </div>
    </div>

    <div class="pform__wrap__close">
        <i class="gg-close"></i>
    </div>
</div>

<div class="pform__wrap__wrapper">

</div>

templates/products/blocks/product_single.html
{% load products_extras %}
{% load static %}
<div class="product__item">
    <div class="product__item__image">
        

        {% if product.has_sale %}
        {% include './svg_fire.html' %}
        <div class="product__item__sale_hint">
            <span>
                - {{ product.discount_perc }} %
            </span>
        </div>
        {% endif %}

        {% modify_imgsrc product.imgsrc as imgsrc %}
        <a href="{% url 'products:product' product.id %}">
        <img src="{% static 'images/products'%}{{imgsrc}}" alt="">
        </a>
    </div>

    <div class="product__item__info">

        <div class="product__item__price">
        
        {% if product.has_sale %}
        
            <span class="product__item__price__sale"> 
                {{ product.sale_price }} Р
            </span>
            <span class="product__item__price__regular">
                {{ product.price }}
            </span>
            {% else %}
            <span class="product__item__price__regular2"> 
                {{ product.price }} Р
            </span>
        {% endif %}
            <div class="product__item__like">
                <!-- <i class="gg-heart"></i> -->
            {% is_in_favorite product.id session_key as in_favorite %}
                {% if in_favorite %}
                <i class="fas fa-heart
                    add_delete_favorite
                    red"
                    value="{{ product.id }}">
                </i>
                    {% else %}
                    <i class="fas fa-heart
                    add_delete_favorite
                    white"
                    value="{{ product.id }}">
                    </i>
                {% endif %}
               
                </i>
            </div>
        </div>
        <a class="product__item__name"
        href="{% url 'products:product' product.id %}">
            {{ product.name }}
        </a>
        <div class="product__item__addcart
        product__addtocart__global"
        value="{{ product.id }}">
        {% is_in_cart product.id cart as in_cart %} 
            {% if in_cart %}
            <span class="in__cart__buttonstyle">
            Удалить с корзины
            </span>
            {% else %}
                <span class="not__incart__buttonstyle">
                    В корзину
                </span>
            {% endif %}
        </div>
    </div>

</div>

templates/products/blocks/products_list.html
{% load el_pagination_tags %}

    {% paginate products %}


    {% include './products_list_products.html' %}


{% show_more %}



    


    <script>
    $(document).ready(function() {
        $.endlessPaginate({
            paginateOnScroll: true,
            onCompleted: function() {
                $(".endless_more").html("Показать еще")
            }
        });
    })
        
    </script>

templates/products/blocks/products_list_products.html
{% load el_pagination_tags %}


{% for product in products  %}
        {% include './product_single.html' %}
{% endfor %}

templates/products/blocks/products_slider.html
<div class="products__slider__wrapper">


<div class="products__slider__main owl-carousel owl-theme">
    {% for product in stock_products  %}
        <div class="products__margin__center">
        {% include './product_single.html' %}
        </div>
    {% endfor %}
    
</div>

{% comment %} <span class="main_slider_arrow2 prev_pr"
id="prev_pr1">
    <i class="gg-chevron-left"></i>
</span>
<span class="main_slider_arrow2 next_pr"
id="next_pr1">
    <i class="gg-chevron-right"></i>
</span> {% endcomment %}

</div>


<script>

</script>

templates/products/blocks/scroll_to_top.html
<div class="scroll_top">
    <i class="fa fa-chevron-up" id="scroll_top_link"></i>
</div>

templates/products/blocks/search_results.html
{% load products_extras %}
{% load static %}

<div class="search__results">

    {% if filter_items.count > 0 %}

    <span class="goods_found">
    Товаров найдено:
    <span>
         {{ items_count }} 
    </span>
    </span>
    
    {% for item in filter_items  %}
    <a class="search__result__item"
    href="{% url 'products:product' item.id %}">
        <div class="search__result__item__img">
        {% modify_imgsrc item.imgsrc as imgsrc %}
            <img src="{% static 'images/products'%}{{imgsrc}}" alt="">
        </div>
        <div class="search__result__item__info">
            <div class="search__result__item__name">
                {{ item.name }}
            </div>
            <div class="search__result__item__price">
                {{ item.price }}
            </div>
        </div>  
    </a>
    {% endfor %}

    <div class="search__results__button">
    <span class="search__results__button__link">
        Смотреть все    
    </span>
    </div>

    {% else %}
        <div class="title_medium_grey">
        Товаров не найдено
        </div>

    {% endif %}
</div>

templates/products/blocks/space10.html
<div class="space__10">
    ------
</div>